<a href="https://colab.research.google.com/github/vjaswanthvarma/ML-projects/blob/main/Naive_bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
import numpy as np
import pandas as pd
from sklearn import datasets

In [32]:
# import wine data set
df=datasets.load_wine()

In [33]:
# sperate the features and ouput
x=df.data
y=df.target

In [34]:
#spilting a data set into training and testing
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [35]:
#Import the naive_bayes classifer
from sklearn.naive_bayes import GaussianNB
nb=GaussianNB()
nb.fit(x_train,y_train)

GaussianNB()

In [40]:
# show a shape of the training and testing
print(x_train.shape)
print(x_test.shape)

(142, 13)
(36, 13)


In [36]:
# predict the output
y_pred=nb.predict(x_test)
y_pred

array([0, 2, 1, 0, 1, 1, 0, 2, 1, 1, 2, 2, 0, 0, 2, 1, 0, 0, 2, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 2, 0, 0, 1, 0, 0, 0])

In [37]:
# Calculate the accuracy of a model
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score,confusion_matrix,accuracy_score
print("mean absolute error",mean_absolute_error(y_test,y_pred))
print("mean squared error",mean_squared_error(y_test,y_pred))
print("mean absolute error",np.sqrt(mean_squared_error(y_test,y_pred)))
print("r2_score",r2_score(y_test,y_pred))
print("Accuracy score",accuracy_score(y_test,y_pred))

mean absolute error 0.08333333333333333
mean squared error 0.08333333333333333
mean absolute error 0.28867513459481287
r2_score 0.8353658536585366
Accuracy score 0.9166666666666666


In [38]:
# Show a confusion Matrix
print(confusion_matrix(y_test,y_pred))

[[14  0  0]
 [ 2 13  1]
 [ 0  0  6]]


In [39]:
# Show a classification report
from sklearn.metrics import classification_report
print("classification_report",classification_report(y_test,y_pred))


classification_report               precision    recall  f1-score   support

           0       0.88      1.00      0.93        14
           1       1.00      0.81      0.90        16
           2       0.86      1.00      0.92         6

    accuracy                           0.92        36
   macro avg       0.91      0.94      0.92        36
weighted avg       0.93      0.92      0.92        36

